<a href="https://colab.research.google.com/github/AnushkaShrivastava28/Airbnd-Data-Analytics-Project/blob/main/Data_Exploration_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Exploration using SQLite and Pandas Dataframe

**Importing Libraries**

In [1]:
import pandas as pd
import numpy as np
import sqlite3

**Importing Dataset**

In [3]:
data = pd.read_csv('Airbnb.csv')
data.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,362,Kavya Iyer,88018,Kavya Iyer,Jaipur,C Scheme,26.879660,75.825309,Private room,2356.0,4,67,2023-06-24,2.34,5,48
1,74,Karan Malhotra,98647,Karan Malhotra,Central Kolkata,Park Street,22.620204,88.292602,Entire home/apt,9209.0,2,0,NaN,NaN,4,115
2,375,Rohan Patel,78656,Rohan Patel,Jaipur,Mansarovar,26.881098,75.763871,Entire home/apt,10148.0,2,15,2025-12-08,1.66,1,361
3,156,Amit Jain,98150,Amit Jain,Udaipur,Hathi Pol,24.592350,73.662297,Private room,1336.0,30,59,2023-06-25,1.21,1,306
4,105,Pooja Mishra,35430,Pooja Mishra,Bhopal,MP Nagar,23.343002,77.448109,Entire home/apt,12236.0,1,57,2023-09-19,4.32,1,240

**Connecting sqlite database**

In [4]:
conn = sqlite3.connect('airbnb_database.db')#this is database name

In [5]:
#now lets make an table and import all data in sqlite3
# if exist mean if before table hai to replace and also index false mean index ko load mat kro wrna ek extra column add
data.to_sql('airbnb_table', conn, if_exists='replace', index=False)

500

In [6]:
query = 'SELECT * From airbnb_table'
pd.read_sql(query, conn)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,362,Kavya Iyer,88018,Kavya Iyer,Jaipur,C Scheme,26.879660,75.825309,Private room,2356.0,4,67,2023-06-24,2.34,5,48
1,74,Karan Malhotra,98647,Karan Malhotra,Central Kolkata,Park Street,22.620204,88.292602,Entire home/apt,9209.0,2,0,None,NaN,4,115
2,375,Rohan Patel,78656,Rohan Patel,Jaipur,Mansarovar,26.881098,75.763871,Entire home/apt,10148.0,2,15,2025-12-08,1.66,1,361
3,156,Amit Jain,98150,Amit Jain,Udaipur,Hathi Pol,24.592350,73.662297,Private room,1336.0,30,59,2023-06-25,1.21,1,306
4,105,Pooja Mishra,35430,Pooja Mishra,Bhopal,MP Nagar,23.343002,77.448109,Entire home/apt,12236.0,1,57,2023-09-19,4.32,1,240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,107,Sneha Nair,22021,Sneha Nair,Ahmedabad,Maninagar,23.023469,72.575858,Hotel room,5861.0,1,110,2023-10-31,5.05,1,223
496,271,Sneha Nair,84057,Sneha Nair,Western Suburbs,Andheri West,19.105271,72.878794,Entire home/apt,12246.0,1,21,2023-10-08,NaN,4,295
497,349,Meera Menon,30174,Meera Menon,Gurgaon,Sector 29,28.522776,77.038877,Private room,2289.0,3,75,2026-05-17,1.30,1,330
498,436,Amit Jain,62692,Amit Jain,Noida,Sector 44,28.485923,77.434229,Entire home/apt,3364.0,4,3,2024-04-27,0.00,1,347
499,103,Rahul Mehta,30308,Rahul Mehta,South Bengaluru,HSR Layout,12.965058,77.592927,Entire home/apt,2307.0,7,11,2025-08-19,2.15,1,70

In [8]:
query = 'SELECT * FROM airbnb_table'
pd.read_sql(query, conn)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,362,Kavya Iyer,88018,Kavya Iyer,Jaipur,C Scheme,26.879660,75.825309,Private room,2356.0,4,67,2023-06-24,2.34,5,48
1,74,Karan Malhotra,98647,Karan Malhotra,Central Kolkata,Park Street,22.620204,88.292602,Entire home/apt,9209.0,2,0,None,NaN,4,115
2,375,Rohan Patel,78656,Rohan Patel,Jaipur,Mansarovar,26.881098,75.763871,Entire home/apt,10148.0,2,15,2025-12-08,1.66,1,361
3,156,Amit Jain,98150,Amit Jain,Udaipur,Hathi Pol,24.592350,73.662297,Private room,1336.0,30,59,2023-06-25,1.21,1,306
4,105,Pooja Mishra,35430,Pooja Mishra,Bhopal,MP Nagar,23.343002,77.448109,Entire home/apt,12236.0,1,57,2023-09-19,4.32,1,240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,107,Sneha Nair,22021,Sneha Nair,Ahmedabad,Maninagar,23.023469,72.575858,Hotel room,5861.0,1,110,2023-10-31,5.05,1,223
496,271,Sneha Nair,84057,Sneha Nair,Western Suburbs,Andheri West,19.105271,72.878794,Entire home/apt,12246.0,1,21,2023-10-08,NaN,4,295
497,349,Meera Menon,30174,Meera Menon,Gurgaon,Sector 29,28.522776,77.038877,Private room,2289.0,3,75,2026-05-17,1.30,1,330
498,436,Amit Jain,62692,Amit Jain,Noida,Sector 44,28.485923,77.434229,Entire home/apt,3364.0,4,3,2024-04-27,0.00,1,347
499,103,Rahul Mehta,30308,Rahul Mehta,South Bengaluru,HSR Layout,12.965058,77.592927,Entire home/apt,2307.0,7,11,2025-08-19,2.15,1,70

**WHERE Room type = Private room**

In [9]:
query = 'SELECT * FROM airbnb_table WHERE room_type = "Private room"'
pd.read_sql(query, conn)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,362,Kavya Iyer,88018,Kavya Iyer,Jaipur,C Scheme,26.879660,75.825309,Private room,2356.0,4,67,2023-06-24,2.34,5,48
1,156,Amit Jain,98150,Amit Jain,Udaipur,Hathi Pol,24.592350,73.662297,Private room,1336.0,30,59,2023-06-25,1.21,1,306
2,395,Amit Jain,98892,Amit Jain,Lucknow,Hazratganj,26.912899,80.930027,Private room,3272.0,7,0,None,NaN,2,289
3,378,Simran Kaur,74414,None,Central Chennai,Adyar,13.071533,80.242839,Private room,1283.0,2,29,2024-08-12,1.47,1,198
4,125,Vikram Joshi,42847,Vikram Joshi,Chandigarh,Sector 17,30.703337,76.781905,Private room,1855.0,1,78,None,3.21,7,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,331,Kavya Iyer,73782,Kavya Iyer,Udaipur,Fateh Sagar,24.621013,73.805711,Private room,2178.0,4,31,2023-10-24,0.42,2,161
163,215,Meera Menon,35614,Meera Menon,North Goa,Calangute,15.506171,73.829130,Private room,5024.0,2,125,2024-02-09,4.74,1,252
164,467,Simran Kaur,49343,Simran Kaur,Lucknow,Gomti Nagar,26.874372,80.877246,Private room,5219.0,2,89,None,NaN,1,134
165,72,Priya Verma,94717,Priya Verma,Jaipur,Malviya Nagar,26.959926,75.772134,Private room,2369.0,1,180,2025-12-10,2.84,3,321
166,349,Meera Menon,30174,Meera Menon,Gurgaon,Sector 29,28.522776,77.038877,Private room,2289.0,3,75,2026-05-17,1.30,1,330

**query to find neighbourhood = Mahanagar**

In [11]:
query = 'SELECT * FROM airbnb_table WHERE neighbourhood = "Mahanagar" '
pd.read_sql(query, conn)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,372,Simran Kaur,53721,Simran Kaur,Lucknow,Mahanagar,26.851012,80.965502,Entire home/apt,4611.0,2,47,None,0.00,8,156
1,492,Kavya Iyer,38059,Kavya Iyer,Lucknow,Mahanagar,26.873723,80.985105,Private room,3306.0,1,42,2026-04-15,0.70,5,274
2,498,Priya Verma,94448,Priya Verma,Lucknow,Mahanagar,26.788304,80.899709,Hotel room,4568.0,1,70,2025-02-25,0.94,3,90
3,78,Pooja Mishra,81364,None,Lucknow,Mahanagar,26.848602,81.025852,Entire home/apt,6063.0,2,58,2026-02-25,2.61,20,188
4,12,Pooja Mishra,95180,Pooja Mishra,Lucknow,Mahanagar,26.817327,80.935378,Entire home/apt,9922.0,7,108,2024-12-17,3.08,1,343
5,132,Priya Verma,57964,Priya Verma,Lucknow,Mahanagar,26.806809,80.899249,Shared room,1491.0,1,69,2025-03-24,2.23,4,206
6,484,Simran Kaur,18942,Simran Kaur,Lucknow,Mahanagar,26.844103,80.984261,Entire home/apt,13662.0,1,108,2025-12-15,3.19,1,27
7,181,Pooja Mishra,96193,Pooja Mishra,Lucknow,Mahanagar,26.858406,80.969249,Entire home/apt,9595.0,3,88,2026-03-26,2.29,1,127
8,391,Simran Kaur,83745,Simran Kaur,Lucknow,Mahanagar,26.902198,80.973485,Hotel room,10901.0,5,102,2024-09-22,0.00,8,314
9,179,Nikhil Rao,13527,Nikhil Rao,Lucknow,Mahanagar,26.868853,80.953302,Private room,3591.0,1,119,2023-08-26,0.86,1,281
10,136,Sahil Khan,95929,Sahil Khan,Lucknow,Mahanagar,26.818053,80.893603,Entire home/apt,1968.0,14,61,2026-07-24,3.96,2,135
11,92,Ananya Singh,53007,Ananya Singh,Lucknow,Mahanagar,26.897252,80.977212,Private room,2380.0,1,95,2025-12-09,0.00,4,148

**All details with availability_365 exist**

In [13]:
# find all details with availability _365 exist
querr = 'SELECT * FROM airbnb_table WHERE availability_365 = 365'
pd.read_sql(query, conn)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,372,Simran Kaur,53721,Simran Kaur,Lucknow,Mahanagar,26.851012,80.965502,Entire home/apt,4611.0,2,47,None,0.00,8,156
1,492,Kavya Iyer,38059,Kavya Iyer,Lucknow,Mahanagar,26.873723,80.985105,Private room,3306.0,1,42,2026-04-15,0.70,5,274
2,498,Priya Verma,94448,Priya Verma,Lucknow,Mahanagar,26.788304,80.899709,Hotel room,4568.0,1,70,2025-02-25,0.94,3,90
3,78,Pooja Mishra,81364,None,Lucknow,Mahanagar,26.848602,81.025852,Entire home/apt,6063.0,2,58,2026-02-25,2.61,20,188
4,12,Pooja Mishra,95180,Pooja Mishra,Lucknow,Mahanagar,26.817327,80.935378,Entire home/apt,9922.0,7,108,2024-12-17,3.08,1,343
5,132,Priya Verma,57964,Priya Verma,Lucknow,Mahanagar,26.806809,80.899249,Shared room,1491.0,1,69,2025-03-24,2.23,4,206
6,484,Simran Kaur,18942,Simran Kaur,Lucknow,Mahanagar,26.844103,80.984261,Entire home/apt,13662.0,1,108,2025-12-15,3.19,1,27
7,181,Pooja Mishra,96193,Pooja Mishra,Lucknow,Mahanagar,26.858406,80.969249,Entire home/apt,9595.0,3,88,2026-03-26,2.29,1,127
8,391,Simran Kaur,83745,Simran Kaur,Lucknow,Mahanagar,26.902198,80.973485,Hotel room,10901.0,5,102,2024-09-22,0.00,8,314
9,179,Nikhil Rao,13527,Nikhil Rao,Lucknow,Mahanagar,26.868853,80.953302,Private room,3591.0,1,119,2023-08-26,0.86,1,281
10,136,Sahil Khan,95929,Sahil Khan,Lucknow,Mahanagar,26.818053,80.893603,Entire home/apt,1968.0,14,61,2026-07-24,3.96,2,135
11,92,Ananya Singh,53007,Ananya Singh,Lucknow,Mahanagar,26.897252,80.977212,Private room,2380.0,1,95,2025-12-09,0.00,4,148

**Closing the connection**

In [14]:
conn.close()

**Reconnecting to SQLite Database**

In [15]:
conn = sqlite3.connect('airbnb_database.db')

# SQL Query With Pandas Dataframe

In [16]:
pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pandasql) (2.1.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from pandasql) (2.2.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (from pandasql) (2.0.52)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->pandasql) (2026.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->pandasql) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->pandasql) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26867 sha256=fb34e1923095b872add667e4bba4f6c310ad2f295afd17d534180396a0ebcc79
  Stored in directory: /root/.cache/pip/wheels/b4/d0/8c/a6b366870bf041849cd96e03b71641e082f8d6456269b603b7
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [17]:
import pandas as pd
from pandasql import sqldf

In [18]:
data = pd.read_csv('Airbnb.csv')

In [19]:
#create the dtaframe df= pd.DataFrame({'Name' : ['John','Bob']
#etc etc }) but i am choosing difficult one

#lets define the query
query = ("select * from data")

#Execute the sql query on data frame
#result = sqldf(query)
#result by this also will get same value what we wanted

sqldf(query)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,362,Kavya Iyer,88018,Kavya Iyer,Jaipur,C Scheme,26.879660,75.825309,Private room,2356.0,4,67,2023-06-24,2.34,5,48
1,74,Karan Malhotra,98647,Karan Malhotra,Central Kolkata,Park Street,22.620204,88.292602,Entire home/apt,9209.0,2,0,None,NaN,4,115
2,375,Rohan Patel,78656,Rohan Patel,Jaipur,Mansarovar,26.881098,75.763871,Entire home/apt,10148.0,2,15,2025-12-08,1.66,1,361
3,156,Amit Jain,98150,Amit Jain,Udaipur,Hathi Pol,24.592350,73.662297,Private room,1336.0,30,59,2023-06-25,1.21,1,306
4,105,Pooja Mishra,35430,Pooja Mishra,Bhopal,MP Nagar,23.343002,77.448109,Entire home/apt,12236.0,1,57,2023-09-19,4.32,1,240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,107,Sneha Nair,22021,Sneha Nair,Ahmedabad,Maninagar,23.023469,72.575858,Hotel room,5861.0,1,110,2023-10-31,5.05,1,223
496,271,Sneha Nair,84057,Sneha Nair,Western Suburbs,Andheri West,19.105271,72.878794,Entire home/apt,12246.0,1,21,2023-10-08,NaN,4,295
497,349,Meera Menon,30174,Meera Menon,Gurgaon,Sector 29,28.522776,77.038877,Private room,2289.0,3,75,2026-05-17,1.30,1,330
498,436,Amit Jain,62692,Amit Jain,Noida,Sector 44,28.485923,77.434229,Entire home/apt,3364.0,4,3,2024-04-27,0.00,1,347
499,103,Rahul Mehta,30308,Rahul Mehta,South Bengaluru,HSR Layout,12.965058,77.592927,Entire home/apt,2307.0,7,11,2025-08-19,2.15,1,70

**Query WHERE room type = Share rooms**

In [20]:
query = ('SELECT * FROM data WHERE room_type = "Shared room" ')
sqldf(query)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,10,Simran Kaur,52487,Simran Kaur,Chandigarh,Sector 17,30.717178,76.816399,Shared room,2355.0,1,23,2023-09-26,0.00,7,306
1,132,Priya Verma,57964,Priya Verma,Lucknow,Mahanagar,26.806809,80.899249,Shared room,1491.0,1,69,2025-03-24,2.23,4,206
2,40,Nikhil Rao,37742,Nikhil Rao,Udaipur,Lake Pichola,24.577579,73.737490,Shared room,587.0,3,60,2026-06-06,NaN,1,167
3,269,Riya Das,72684,Riya Das,North Goa,Anjuna,15.508531,73.848184,Shared room,1053.0,4,67,2024-02-25,1.27,1,197
4,4,Arjun Kapoor,59823,Arjun Kapoor,Jaipur,Mansarovar,26.880619,75.737869,Shared room,1127.0,1,103,2026-04-06,0.00,6,51
5,359,Meera Menon,59160,Meera Menon,Bhopal,Kolar Road,23.200229,77.332905,Shared room,1825.0,3,94,2025-05-12,5.03,2,109
6,361,Arjun Kapoor,40539,Arjun Kapoor,Western Suburbs,Colaba,19.060767,72.903971,Shared room,1291.0,1,74,2024-08-26,2.12,7,127
7,39,Ishita Roy,26728,Ishita Roy,Udaipur,Ambamata,24.551694,73.746701,Shared room,1744.0,2,47,2024-06-10,6.42,3,239
8,470,Rahul Mehta,79417,Rahul Mehta,North Goa,Baga,15.583098,73.799621,Shared room,1441.0,1,88,2024-09-17,NaN,1,149
9,430,Simran Kaur,60387,Simran Kaur,Gurgaon,Sector 29,28.442413,77.062560,Shared room,2770.0,2,45,2026-04-26,3.04,2,1
10,157,Riya Das,92050,Riya Das,Central Chennai,Velachery,13.035391,80.236544,Shared room,1239.0,1,0,None,NaN,9,89
11,307,Sneha Nair,96652,Sneha Nair,Western Suburbs,Juhu,19.104996,72.845265,Shared room,1677.0,2,52,2025-10-29,0.00,1,60
12,122,Pooja Mishra,13445,Pooja Mishra,Udaipur,Shobhagpura,24.588747,73.681531,Shared room,1279.0,2,48,2025-12-06,3.32,1,252

**Number of Room types**

In [21]:
query = ('SELECT room_type, count(*) FROM data GROUP BY room_type')
sqldf(query)

         room_type  count(*)
0  Entire home/apt       282
1       Hotel room        38
2     Private room       167
3      Shared room        13

In [25]:
data['room_type'].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'],
      dtype=object)

**Check correlation**

In [26]:
data.corr(numeric_only=True)

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
id,1.000000,-0.005467,0.035125,-0.066747,0.036011,-0.025859,0.010079,0.018539,-0.082995,0.016954
host_id,-0.005467,1.000000,0.079421,-0.089535,0.030140,-0.017165,0.039819,-0.010111,-0.003394,-0.048715
latitude,0.035125,0.079421,1.000000,0.127047,0.000743,-0.005450,0.027789,0.017842,-0.041689,0.047597
longitude,-0.066747,-0.089535,0.127047,1.000000,-0.133148,0.037983,0.007996,-0.079440,-0.054975,-0.024874
price,0.036011,0.030140,0.000743,-0.133148,1.000000,0.049943,-0.024959,0.039110,-0.066271,0.024042
minimum_nights,-0.025859,-0.017165,-0.005450,0.037983,0.049943,1.000000,-0.035528,-0.035880,-0.008629,0.023065
number_of_reviews,0.010079,0.039819,0.027789,0.007996,-0.024959,-0.035528,1.000000,-0.046144,-0.072049,0.019475
reviews_per_month,0.018539,-0.010111,0.017842,-0.079440,0.039110,-0.035880,-0.046144,1.000000,-0.008438,-0.064124
calculated_host_listings_count,-0.082995,-0.003394,-0.041689,-0.054975,-0.066271,-0.008629,-0.072049,-0.008438,1.000000,0.049108
availability_365,0.016954,-0.048715,0.047597,-0.024874,0.024042,0.023065,0.019475,-0.064124,0.049108,1.000000